name: Python Greetings Delivery Pipeline

on:
    push:
        branches: [ main ]

jobs:
    install-pip-deps:
        name: Install Pip Dependencies
        runs-on: self-hosted
        steps:
          - name: Checkout delivery pipeline definition
            uses: actions/checkout@v3.5.2
          - name: Checkout python-greetings repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/python-greetings
              path: python-greetings
          - name: Install pip dependencies
            working-directory: python-greetings
            run: |
              pip3 install -r requirements.txt

    deploy-to-dev:
        name: Deploy to Development
        runs-on: self-hosted
        needs: [install-pip-deps]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone python-greetings repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/python-greetings
              path: python-greetings
          - name: Stop existing development environment
            run: |
              pm2 delete greetings-app-dev; exit 0
            working-directory: python-greetings
          - name: Start development environment
            run: |
              $env:PORT = 7001
              pm2 start app.py --name greetings-app-dev
            working-directory: python-greetings
          

    tests-on-dev:
        name: Run Tests on Development
        runs-on: self-hosted
        needs: [deploy-to-dev]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Run tests on development environment
            run: |
        
    deploy-to-staging:
        name: Deploy to Staging
        runs-on: self-hosted
        needs: [tests-on-dev]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Deploy to staging environment
            run: |
         

    tests-on-staging:
        name: Run Tests on Staging
        runs-on: self-hosted
        needs: [deploy-to-staging]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Run tests on staging environment
            run: |

    deploy-to-preprod:
        name: Deploy to Preprod
        runs-on: self-hosted
        needs: [tests-on-staging]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Deploy to preprod environment
            run: |

    tests-on-preprod:
        name: Run Tests on Preprod
        runs-on: self-hosted
        needs: [deploy-to-preprod]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Run tests on preprod environment
            run: |
        

    deploy-to-prod:
        name: Deploy to Production
        runs-on: self-hosted
        needs: [tests-on-preprod]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Deploy to production environment
            run: |
          

    tests-on-prod:
        name: Run Tests on Production
        runs-on: self-hosted
        needs: [deploy-to-prod]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Run tests on production environment
            run: |
          