name: Python Greetings Delivery Pipeline

on:
    push:
        branches: [ main ]

jobs:
    install-pip-deps:
        name: Install Pip Dependencies
        runs-on: self-hosted
        steps:
          - uses: ./.github/act/install/install.yml

    deploy-to-dev:
        name: Deploy to Development
        runs-on: self-hosted
        needs: [install-pip-deps]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone python-greetings repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/python-greetings
              path: python-greetings
          - name: Stop existing development environment
            run: |
              pm2 delete greetings-app-dev; exit 0
            working-directory: python-greetings
          - name: Start development environment
            run: |
              $env:PORT = 7001
              pm2 start app.py --name greetings-app-dev
            working-directory: python-greetings
          

    tests-on-dev:
        name: Run Tests on Development
        runs-on: self-hosted
        needs: [deploy-to-dev]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone course-js-api-framework repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/course-js-api-framework
              path: course-js-api-framework
          - name: Install dependencies
            run: npm install
            working-directory: course-js-api-framework
          - name: Run tests
            run: npm run greetings greetings_dev
            working-directory: course-js-api-framework
        
    deploy-to-staging:
        name: Deploy to Staging
        runs-on: self-hosted
        needs: [tests-on-dev]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone python-greetings repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/python-greetings
              path: python-greetings
          - name: Stop existing staging environment
            run: |
              pm2 delete greetings-app-staging; exit 0
            working-directory: python-greetings
          - name: Start staging environment
            run: |
              $env:PORT = 7002
              pm2 start app.py --name greetings-app-staging
            working-directory: python-greetings
         

    tests-on-staging:
        name: Run Tests on Staging
        runs-on: self-hosted
        needs: [deploy-to-staging]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone course-js-api-framework repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/course-js-api-framework
              path: course-js-api-framework
          - name: Install dependencies
            run: npm install
            working-directory: course-js-api-framework
          - name: Run tests
            run: npm run greetings greetings_stg
            working-directory: course-js-api-framework

    deploy-to-preprod:
        name: Deploy to Preprod
        runs-on: self-hosted
        needs: [tests-on-staging]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone python-greetings repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/python-greetings
              path: python-greetings
          - name: Stop existing preprod environment
            run: |
              pm2 delete greetings-app-preprod; exit 0
            working-directory: python-greetings
          - name: Start preprod environment
            run: |
              $env:PORT = 7003
              pm2 start app.py --name greetings-app-preprod
            working-directory: python-greetings

    tests-on-preprod:
        name: Run Tests on Preprod
        runs-on: self-hosted
        needs: [deploy-to-preprod]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone course-js-api-framework repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/course-js-api-framework
              path: course-js-api-framework
          - name: Install dependencies
            run: npm install
            working-directory: course-js-api-framework
          - name: Run tests
            run: npm run greetings greetings_prod
            working-directory: course-js-api-framework
        

    deploy-to-prod:
        name: Deploy to Production
        runs-on: self-hosted
        needs: [tests-on-preprod]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone python-greetings repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/python-greetings
              path: python-greetings
          - name: Stop existing prod environment
            run: |
              pm2 delete greetings-app-prod; exit 0
            working-directory: python-greetings
          - name: Start prod environment
            run: |
              $env:PORT = 7004
              pm2 start app.py --name greetings-app-prod
            working-directory: python-greetings
          

    tests-on-prod:
        name: Run Tests on Production
        runs-on: self-hosted
        needs: [deploy-to-prod]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3.5.2
          - name: Clone course-js-api-framework repository
            uses: actions/checkout@v3.5.2
            with:
              repository: rtwork321/course-js-api-framework
              path: course-js-api-framework
          - name: Install dependencies
            run: npm install
            working-directory: course-js-api-framework
          - name: Run tests
            run: npm run greetings greetings_prod
            working-directory: course-js-api-framework
          